name: Build Android APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Capacitor
        run: |
          npm install @capacitor/core @capacitor/cli @capacitor/android
          mkdir -p www
          cp index.html www/

      - name: Initialize Android
        run: |
          rm -rf android
          npx cap init "King Shops" "com.kingshops.game" --web-dir www
          npx cap add android

      - name: Force Icon Replace
        run: |
          # استبدال كل أيقونات أندرويد الافتراضية بصورتك فوراً
          FILE_NAME="1772038628701.png"
          TARGET_DIR="android/app/src/main/res"
          
          for dir in $TARGET_DIR/mipmap-*; do
            cp "$FILE_NAME" "$dir/ic_launcher.png"
            cp "$FILE_NAME" "$dir/ic_launcher_round.png"
          done

      - name: Build APK
        run: |
          npx cap copy
          cd android && ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: King-Shops-Final-Version
          path: android/app/build/outputs/apk/debug/app-debug.apk
